#!/usr/bin/env python3
"""
The data types for an Ocean Salinity UDP
"""

import numpy as np

datatype = [
    (
        "Grid_Point_Data",
        [
            ("Grid_Point_ID", np.uint32),
            ("Latitude", np.float32),
            ("Longitude", np.float32),
        ],
    ),
    (
        "Geophysical_Parameters_Data",
        [
            ("Equiv_ftprt_diam", np.float32),
            ("Mean_acq_time", np.float32),
            ("SSS1", np.float32),
            ("Sigma_SSS1", np.float32),
            ("SSS2", np.float32),
            ("Sigma_SSS2", np.float32),
            ("SSS3", np.float32),
            ("Sigma_SSS3", np.float32),
            ("A_card", np.float32),
            ("Sigma_A_card", np.float32),
            ("WS", np.float32),
            ("SST", np.float32),
            ("Tb_42_5H", np.float32),
            ("Sigma_Tb_42_5H", np.float32),
            ("Tb_42_5V", np.float32),
            ("Sigma_Tb_42_5V", np.float32),
            ("Tb_42_5X", np.float32),
            ("Sigma_Tb_42_5X", np.float32),
            ("Tb_42_5Y", np.float32),
            ("Sigma_Tb_42_5Y", np.float32),
        ],
    ),
    ("Control_Flags_1", np.uint32),
    ("Control_Flags_2", np.uint32),
    ("Control_Flags_3", np.uint32),
    ("Control_Flags_4", np.uint32),
    (
        "Product_Confidence_Descriptors",
        [
            ("Dg_chi2_1", np.uint16),
            ("Dg_chi2_2", np.uint16),
            ("Dg_chi2_3", np.uint16),
            ("Dg_chi2_Acard", np.uint16),
            ("Dg_chi2_P_1", np.uint16),
            ("Dg_chi2_P_2", np.uint16),
            ("Dg_chi2_P_3", np.uint16),
            ("Dg_chi2_P_Acard", np.uint16),
            ("Dg_quality_SSS1", np.uint16),
            ("Dg_quality_SSS2", np.uint16),
            ("Dg_quality_SSS3", np.uint16),
            ("Dg_quality_Acard", np.uint16),
            ("Dg_num_iter_1", np.uint8),
            ("Dg_num_iter_2", np.uint8),
            ("Dg_num_iter_3", np.uint8),
            ("Dg_num_iter_4", np.uint8),
            ("Dg_num_meas_l1c", np.uint16),
            ("Dg_num_meas_valid", np.uint16),
            ("Dg_border_fov", np.uint16),
            ("Dg_af_fov", np.uint16),
            ("Dg_sun_tails", np.uint16),
            ("Dg_sun_glint_area", np.uint16),
            ("Dg_sun_glint_fov", np.uint16),
            ("Dg_sun_fov", np.uint16),
            ("Dg_sun_glint_L2", np.uint16),
            ("Dg_Suspect_ice", np.uint16),
            ("Dg_Galactic_Noise_Error", np.uint16),
            ("Dg_sky", np.uint16),
            ("Dg_moon_glint", np.uint16),
            ("Dg_RFI_L1", np.uint16),
            ("Dg_RFI_X", np.uint16),
            ("Dg_RFI_Y", np.uint16),
            ("Dg_RFI_probability", np.uint16),
            ("X_swath", np.float32),
        ],
    ),
    ("Science_Flags_1", np.uint32),
    ("Science_Flags_2", np.uint32),
    ("Science_Flags_3", np.uint32),
    ("Science_Flags_4", np.uint32),
]

control_flags_dtype = [
    ("Fg_ctrl_ignore", bool),
    ("Fg_ctrl_range", bool),
    ("Fg_ctrl_sigma", bool),
    ("Fg_ctrl_chi2", bool),
    ("Fg_ctrl_chi2_P", bool),
    ("Fg_ctrl_contaminated", bool),
    ("Fg_ctrl_sunglint", bool),
    ("Fg_ctrl_moonglint", bool),
    ("Fg_ctrl_gal_noise", bool),
    ("Fg_ctrl_mixed_scene", bool),
    ("Fg_ctrl_reach_maxiter", bool),
    ("Fg_ctrl_num_meas_min", bool),
    ("Fg_ctrl_num_meas_low", bool),
    ("Fg_ctrl_many_outliers", bool),
    ("Fg_ctrl_marq", bool),
    ("Fg_ctrl_roughness", bool),
    ("Fg_ctrl_foam", bool),
    ("Fg_ctrl_ecmwf", bool),
    ("Fg_ctrl_valid", bool),
    ("Fg_ctrl_no_surface", bool),
    ("Fg_ctrl_range_Acard", bool),
    ("Fg_ctrl_sigma_Acard", bool),
    ("SPARE", bool),
    ("Fg_ctrl_used_faraTEC", bool),
    ("Fg_ctrl_poor_geophysical", bool),
    ("Fg_ctrl_poor_retrieval", bool),
    ("Fg_ctrl_suspect_rfi", bool),
    ("Fg_ctrl_rfi_prone_X", bool),
    ("Fg_ctrl_rfi_prone_Y", bool),
    ("Fg_ctrl_adjusted_ra", bool),
    ("Fg_ctrl_retriev_fail", bool),
]

science_flags_dtype = [
    ("Fg_sc_land_sea_coast1", bool),
    ("Fg_sc_land_sea_coast2", bool),
    ("Fg_sc_TEC_gradient", bool),
    ("Fg_sc_in_clim_ice", bool),
    ("Fg_sc_ice", bool),
    ("Fg_sc_suspect_ice", bool),
    ("Fg_sc_rain", bool),
    ("Fg_sc_high_wind", bool),
    ("Fg_sc_low_wind", bool),
    ("Fg_sc_high_SST", bool),
    ("Fg_sc_low_SST", bool),
    ("Fg_sc_high_SSS", bool),
    ("Fg_sc_low_SSS", bool),
    ("Fg_sc_sea_state_1", bool),
    ("Fg_sc_sea_state_2", bool),
    ("Fg_sc_sea_state_3", bool),
    ("Fg_sc_sea_state_4", bool),
    ("Fg_sc_sea_state_5", bool),
    ("Fg_sc_sea_state_6", bool),
    ("Fg_sc_sst_front", bool),
    ("Fg_sc_sss_front", bool),
    ("Fg_sc_ice_Acard", bool),
    ("Fg_sc_ecmwf_land", bool),
]
